name: windows-pytest

on:
  push:

jobs:
  flake8-pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        poetry-version: [1.1.2]
        # os: [ubuntu-18.04, macos-latest, windows-latest]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install packages
        run: |
          # poetry config virtualenvs.create false
          # pip install pycld2 pyicu fasttest
          if [ "$RUNNER_OS" == "Linux" ]; then
            # apt install important_linux_software
            echo "$RUNNER_OS do nothing"
            # exit 0
          elif [ "$RUNNER_OS" == "Windows" ]; then
            # poetry run pip install data\\artifects\\pycld2-0.41-cp38-cp38-win_amd64.whl
            # poetry add git+https://github.com/aboSamoor/polyglot@master
            # poetry run pip install data\\artifects\\PyICU-2.9-cp38-cp38-win_amd64.whl
            pip install -r requirements.txt
          else
            echo "$RUNNER_OS do nothing"
            # exit 0
          fi
          # poetry install  # --no-dev
        shell: bash
      - name: Run flake8
        run: |
          poetry run flake8 --exit-zero
          # poetry run pytest
      - name: Run pytest
        run: poetry run pytest tests
